spring:
  application:
    name: kopring
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: mysql
  security:
    oauth2:
      client:
        registration:
          github:
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope:
              - read:user
              - repo
              - user:email
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
debug: false

server:
  port: 8080
